### ISSUE TITLE
RTMP unsupported video codec: 2 (MP3)

### ISSUE THREAD

**Issue by tstechnologies** [aler9/mediamtx#1102]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTMP Published stream from DJI device results in closed session. See log excerpt below (ips obfuscated):

Aug 18 21:54:49 HOSTNAME rtsp-simple-server[114]: 2022/08/18 21:54:49 INF [RTMP] [conn 0.0.0.0:10751] closed (unsupported video codec: 2)

ffmpeg version 4.2.7-0ubuntu0.1

Installed all media codecs with `sudo apt install ubuntu-restricted-extras`

## Describe how to replicate the issue

1. start the server
2. publish with dji go application (RTMP)
3. read with VLC (obviously shows no alias/stream available)

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, please provide a network dump, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

Thanks

**Comment by aler9** [comment]
The server now supports publishing reading and proxying MP3 tracks with RTMP.

**Comment by aler9** [comment]
added in v0.23.0
