### ISSUE TITLE
Support for Enhanced RTMP

### ISSUE THREAD

**Issue by Docteh** [aler9/mediamtx#1621]
## Describe the feature

OBS 29.1 has support for additional RTMP codecs via an [Enhanced RTMP](https://github.com/veovera/enhanced-rtmp/) standard. I think the  [OBS Pull Request](https://github.com/obsproject/obs-studio/pull/8522) is a good primary source. The enhanced standard adds AV1 H265 and VP9. There has even been some media coverage on the feature via [Tom's Hardware](https://www.tomshardware.com/news/av1-live-streaming-is-finally-coming-to-youtube).

The project README.md mentions H265 support from OBS, but from what I can tell that was due to a bug/feature on OBS end.

To be sure I tried a nightly OBS with rtmp-simple-server 0.21.6, and got the following:
2023/03/28 09:19:18 INF [RTMP] [conn 127.0.0.1:54939] closed (unsupported video codec: 0)
The packet capture is just me verifying that the OBS nightly was sending out the new standard, but using a properly marked OBS 29.1 beta is a better idea https://github.com/obsproject/obs-studio/releases/tag/29.1.0-beta1
![image](https://user-images.githubusercontent.com/190571/228308379-d029bca0-162e-4110-b882-1d8043eecaf4.png)

**Comment by aler9** [comment]
Hello, i'll surely take a look at the specification and use it to improve the server.

Most RTMP software, including OBS, currently declares H265 tracks as H264 tracks, therefore it's enough to discriminate between the two codecs in the initialization phase, and that's why this server supports H265 through RTMP:

https://github.com/aler9/mediamtx/blob/e4268104555c53946eb0adc1f2dad0c1539643f9/internal/rtmp/conn.go#L736

**Comment by aler9** [comment]
all implemented!

**Comment by aler9** [comment]
added in v0.23.0
