### ISSUE TITLE
Set Listen IP on system with multiple interfaces/ip's

### ISSUE THREAD

**Issue by t3therdev** [aler9/mediamtx#914]
## Which version are you using?

v0.18.0

## Which operating system are you using?

- [x ] Windows amd64 standard

## Describe the issue

When using windows version, how do we set what listen address is used for RTSP? we have a system with multiple interfaces and IP's and it doesn't seem to bind to all of them. 

Log is showing this:
2022/04/13 00:06:42 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)

how do we bind it specifically to only one interface and IP address?

only localhost seems to work

seems to be reference to a previous bug with listenIP but not sure where to set it, and its not allowing the exe to start.

**Comment by Tabarane** [comment]
based on my experience when you want to listen on windows to all subnets, you need to actually write the full subnet , using 0.0.0.0 as Linux will not work on Windows and you can this to your path setting i think so

**Comment by MayeulC** [comment]
I am not sure if I should create a new issue for that, but the title of this issue seemed too fitting:

I'd also like to bind to multiple addresses, like:

```yaml
rtspAddress: ['[::1]:8554', 127.0.0.1:8554, 172.17.0.1:8554]
```
This would have saved me some work, though in the end I could do it with socat, although you have to specify interfaces instead of addresses:
```
# 172.17.0.1:8554 -> [::1]:8554
socat TCP4-LISTEN:8554,fork,su=nobody,INTERFACE=docker0 TCP6:[::1]:8554
```

**Comment by aler9** [comment]
In order to bind to a single IP address, it's enough to set the IP inside the the listening address:

```yml
rtspAddress: 192.168.5.98:8554
```

Binding to multiple addresses is a feature that won't be developed because it would require additional code and additional configuration options, while it can be achieved by
* listening on all addresses and using a firewall to filter incoming requests
* alternatively, hosting the server into Docker and using Docker port mapping
